### ISSUE TITLE
Emacs lsp-mode integration

### ISSUE THREAD

**Issue by termlen0** [ansible/ansible-language-server#101]
### Problem

The lsp-mode in emacs makes it possible for emacs users to take advantage of the language servers and there are currently many existing ones. https://emacs-lsp.github.io/lsp-mode/page/languages/ (YAML/Python and even terraform) :)
Adding support for emacs will help a large user base to take advantage of the work done here without having to switch to another editor.

### Solution

Integration for lsp-mode in emacs

**Comment by webknjaz** [comment]
Hi, this repository is dedicated to the language server part that is universal. You seem to be requesting some client-side integration which is out of the scope here. We have a separate repository for the VS Code client extension and we also know about an external community project implementing it for Vim: https://github.com/yaegassy/coc-ansible.

We don't intentionally limit editor support and the LSP is supposed to be agnostic so we welcome the community to make use of this in any way they need to ensure their favorite editor can use the ALS. OTOH, we also do not have any plans to get into the business of creating client-side extensions for every editor possible. At the moment, the only official client-side extension that the Ansible DevTools Team is going to support as employees of Red Hat is https://github.com/ansible/vscode-ansible. If individual community contributors want to make use of the ALS, though, we'll be glad to accept PRs necessary to make this happen.

P.S. I don't personally use Emacs (I'm a NeoVim user) so I can't direct you any further. I think that @relrod is the only one on the team using it so maybe he could point to in the right direction.
