### ISSUE TITLE
Failure to instantiate when missing a workspace

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-language-server#117]
I identified what triggers the ALS to report as being active on an open document but in fact it would not run at all, only syntax highlight seems to be working as that is a passive feature.

This happens when an ansible file is opened directly without having a workspace.

While vscode may remember to open that particular file with Ansible, it will fail to initialize the ALS when doing so, which is clearly visible by the missing `Ansible Server` output pannel.

Initially reported at https://github.com/ansible/vscode-ansible/discussions/316

# Workaround

To avoid this bug just be sure you open entire project folder in vscode, so you do not end-up opening files without having an active workspace. We will likely include a proper fix in the next release.

**Comment by ssbarnea** [comment]
To reproduce the bug in debugger just reconfigure extension to open the sample file directly instead of opening the folder:
![](https://sbarnea.com/ss/Screen-Shot-2021-11-15-17-27-23.21.png)

**Comment by webknjaz** [comment]
cc @yaegassy do you have this problem with the Vim plugin?

**Comment by cidrblock** [comment]
Related: https://github.com/ansible/vscode-ansible/pull/319

(needs to be removed when this issue is resolved)

**Comment by yaegassy** [comment]
I don't know how to reproduce this problem with the vim plugin

Vim plugin (`coc.nvim`) automatically resolves the workspace folder equivalent, so this problem may not occur.

**See**: 

- <https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders>

**Comment by ganeshrn** [comment]
> To reproduce the bug in debugger just reconfigure extension to open the sample file directly instead of opening the folder: ![](https://camo.githubusercontent.com/10ebc8e2f134f86ce901bc15007990f57652e3f54c4670f2bac50065304047b7/68747470733a2f2f736261726e65612e636f6d2f73732f53637265656e2d53686f742d323032312d31312d31352d31372d32372d32332e32312e706e67)

I am not able to reproduce the issue with the steps shared above. Also as the file is opened within `workspaceFolder` the workspace context is properly set in the ansible-language-server and the autocompletion is working fine within `play1.yml` file.


<img width="1421" alt="Screen Shot 2021-11-24 at 9 47 48 AM" src="https://user-images.githubusercontent.com/5292461/143174272-3efb3c8f-8a03-430b-9f4b-63375a4af8de.png">
