### ISSUE TITLE
Add support to create config variables to avoid hard-coded strings

### ISSUE THREAD

**Issue by priyamsahoo** [ansible/ansible-language-server#14]
Supporting config variable is out of the scope as of now. It can be viewed as a separate task and I am going to look into it.

_Originally posted by @priyamsahoo in https://github.com/ansible/ansible-language-server/pull/5#r705234335_

**Comment by webknjaz** [comment]
It looks like this would need client-side support. It should probably send options as in this example: https://github.com/redhat-developer/vscode-java/blob/af081b9/src/standardLanguageClient.ts#L70-L92.

**Comment by webknjaz** [comment]
Our extensions sets those here: https://github.com/ansible/vscode-ansible/blob/5ef7df7/src/extension.ts#L29-L48.

**Comment by priyamsahoo** [comment]
The language server has them [here](https://github.com/ansible/ansible-language-server/blob/5fe20f9/src/services/settingsManager.ts#L15-L20) in this file.
