### ISSUE TITLE
Messages originated from ASL should use language-server-protocol: notificationMessage

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-language-server#15]
After investigation made with @webknjaz yesterday, we concluded that use of `showInformationMessage()` or `showErrorMessage()` inside the language server is wrong as this would prevent use of the language-server on other editors than vscode.

Apparently language-server-protocol has an api that can be used for this use case: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#notificationMessage

The idea is that the ASL should produce the notification and is up to the extension to process it or not. Is not mandatory for each client to implement ability to process these notifications from the language server and that is ok.

One example of processing notifications can be see at https://github.com/redhat-developer/vscode-java/blob/master/src/standardLanguageClient.ts#L152-L181

It worth mentioning that this info was provided by our friends from #devtools-vscode channel from coreos slack instance.

Anyone is welcomed to work on addressing this, just add a comment.

**Comment by priyamsahoo** [comment]
@yaegassy, does this issue affect your dev for the vim extension ?

**Comment by priyamsahoo** [comment]
Ah alright. Thanks for the feedback @yaegassy :)

**Comment by ssbarnea** [comment]
I this is already implemented now, that i how we send info about enviorment.
