### ISSUE TITLE
"listen" is not detected as a keyword

### ISSUE THREAD

**Issue by bluikko** [ansible/ansible-language-server#162]
### Summary

The keyword `listen` is not detected as a keyword. All other keywords seem to be detected, including `notify`.

### Extension version

0.7.1

### VS Code version

1.62.3

### Ansible Version

```shell
Running on Windows without Ansible.
```

### OS / Environment

Windows 10 1909.

### Relevant log output

```shell
Only errors about spawning `cmd` because there is no python or ansible.
```

**Comment by ganeshrn** [comment]
Currently the keywords are hardcoded in file https://github.com/ansible/ansible-language-server/blob/main/src/utils/ansible.ts
To fix this we will have to run `ansible-doc -l -t keyword` command to generate ansible keywords. This feature was added in recent release of ansible-core.
