### ISSUE TITLE
A utility to update settings automatically in readme file

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-language-server#192]
### Problem

Currently the settings supported by language server are manually updated in the README and there are chances that any new settings added will get out of sync in the readme file

### Solution

Based on comment https://github.com/ansible/ansible-language-server/pull/189#issuecomment-1022129802 add a utility to generate setting in README section by parsing the values from within code as shared in comment https://github.com/ansible/ansible-language-server/pull/189#issuecomment-1022709205

**Comment by webknjaz** [comment]
How about just pointing at Sphinx docs that would always have up-to-date info w/o having to commit these changes to the readme.

**Comment by ganeshrn** [comment]
Fixed by https://github.com/ansible/ansible-language-server/pull/294
