### ISSUE TITLE
Command failed error appears when running ansible-lint

### ISSUE THREAD

**Issue by yaegassy** [ansible/ansible-language-server#21]
### Problem

If there are syntax errors problems, you will get a very unimpressive error message.

<img width="1024" alt="2_vscode-ansible-error" src="https://user-images.githubusercontent.com/188642/133185473-1d08321c-570f-4c6c-9aef-2f01bdbf9370.png">

Is it possible for the language server to handle it properly and put it in the diagnostics message?

### Solution

Please add some adjusting here

- https://github.com/ansible/ansible-language-server/blob/main/src/services/ansibleLint.ts#L133-L135

### Additional context

I created an extension to use "ansible-language-server" using `coc.nvim`, a VSCode-like plugin for Vim8/Neovim.

- coc-ansible
  - <https://github.com/yaegassy/coc-ansible>

I was surprised to see a bright red error screen. :(

<img width="953" alt="1_coc-ansible-error" src="https://user-images.githubusercontent.com/188642/133185393-e1257fae-359b-48cf-893d-a8ea82ede752.png">

**Comment by priyamsahoo** [comment]
Hey, thanks for this. The code base is currently going through a major refactoring effort. We don't expect this to be an issue when that work is done. This will remain open until sometime after the new version is released. Please check back in the next month or so.

There's a high chance that this will get fixed after https://github.com/ansible/ansible-language-server/pull/5 is merged!

**Comment by priyamsahoo** [comment]
Also, based on the output, I believe that ansible-lint is either not installed in the env. or not configured properly. 

**For a quick fix, try setting disabling the lint in the settings.json as see if the error shows up or not.**

Nonetheless, it will be fixed in the #5 is merged!

**Comment by priyamsahoo** [comment]
Also, about the solution:

- We have decided to remove all messages (window pop-ups for vscode) originated from the language server. This way, we can keep the ASL agnostic and thus it can be used by ansible extension for any text editor/IDE.

- An issue regarding the same has already been filed: #15

**Comment by yaegassy** [comment]
@priyamsahoo Thanks for the info!!!

I understood that there is already a similar issue.

My extension (`coc-ansible`) for Vim is tuned to automatically set `ansible.ansibleLint.enabled` to `false` if `ansible-lint` is not detected in the current Python environment (including virtual environments).

**Comment by yaegassy** [comment]
This issue is closed because there is a similar issue and it looks like it will be adjusted in the future.
