### ISSUE TITLE
syntax-check error returns invalid character value

### ISSUE THREAD

**Issue by jemag** [ansible/ansible-language-server#218]
### Summary

- Use ansible-language-server on a non-valid yaml file 
- ansible-language-server returns invalid character value:
```
   diagnostics = { {
        message = "[syntax-check] A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead\nDescription: Running ``ansible-playbook --syntax-check ...`` failed.\n\nThis error **cannot be disabled** due to being a prerequisite for other steps.\nYou can either exclude these files from linting or better assure they can be\nloaded by Ansible. This is often achieved by editing inventory file and/or\n``ansible.cfg`` so ansible can load required variables.\n\nIf undefined variables are the failure reason you could use jinja default()\nfilter in order to provide fallback values.\n",
        range = {
          end = {
            character = 9.007199254741e+15,
            line = 1
          },
          start = {
            character = 0,
            line = 1
          }
        },
```
This causes problems as the value is clearly outside the range of any reasonable file.

For full reproducible steps, see: https://github.com/neovim/neovim/issues/17315 (I erroneously reported this as a Neovim bug, but I was then made aware of the improper server response).

### Extension version

n/a

### VS Code version

n/a

### Ansible Version

```shell
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jemag/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/jemag/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

### OS / Environment

Arch Linux/Linux 5.16.2-arch1-1
ansible-language-server/v.0.4.0

**Comment by joshzcold** [comment]
+1 for getting this fixed. causes errors on neovim-lsp

**Comment by joshzcold** [comment]
Looks like the passing of `Number.MAX_SAFE_INTEGER` into type `Range` causes a int -> string conversion
`9007199254740991` => `9.007199254741e+15`
https://github.com/ansible/ansible-language-server/blob/25c500a9e2d966f314ceb97fbba49cb8311782a5/src/services/ansibleLint.ts#L196-L203

**Comment by joshzcold** [comment]
This pull request seems to solve the issue for me:
https://github.com/ansible/ansible-language-server/pull/246

https://user-images.githubusercontent.com/36175703/156818887-413c17ed-51f3-4eed-9178-1fb6ee1940c3.mp4

**Comment by priyamsahoo** [comment]
@jemag , there is nothing wrong with the server's response and just to confirm, server sends that number figure as an appropriate type (Number) that is safe to handle.
The error is because of how the neovim ansible extension (client) is dealing with the response.

In the case of vscode ansible extension, it works absolutely fine, even if the server sends some very large number ( like 10^308) that gets converted to scientific notations.

Still, to support such extensions, I have opened a new PR with appropriate changes: https://github.com/ansible/ansible-language-server/pull/261 and this shall fix the issue.
