### ISSUE TITLE
Fix broken windows platform broken tests

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-language-server#26]
As part of adding CI pipelines via #17 I identified that running tests under windows does not work. This should be a top priority to fix.

**Comment by webknjaz** [comment]
Per the discussion between Ganesh and I on Slack, we should update the Windows jobs to run WSL2 instead of (or additionally to) the native runtime.

**Comment by webknjaz** [comment]
I've added a few `console.log()`s and noticed the difference in that the `getYamlDoc()` helper function in `test/utils/yaml.test.ts` returns a text node containing different line separators on Windows and other platforms (`\r\n` vs. `\n`).
This is created by `TextDocument.create()`[^1] provided by the `vscode-languageserver-textdocument` third-party library. I haven't yet checked what we can/should do about it, though.

```diff
 getPathInFile textDoc FullTextDocument {
   _uri: 'uri',
   _languageId: 'ansible',
   _version: 1,
-  _content: '- name: Test play\n' +
+  _content: '- name: Test play\r\n' +
-    '  hosts: localhost\n' +
+    '  hosts: localhost\r\n' +
-    '  gather_facts: false\n' +
+    '  gather_facts: false\r\n' +
-    '  roles:\n' +
+    '  roles:\r\n' +
-    '    - name: role\n' +
+    '    - name: role\r\n' +
-    '      when: condition\n',
+    '      when: condition\r\n',
   _lineOffsets: undefined
 }
```

Note that I've discovered this while debugging the test `canCorrectlyConfirmRoleParam` but it may be the cause of all the other failures too:
```console
$ npm test -- --grep canCorrectlyConfirmRoleParam
```

[^1]: https://github.com/ansible/ansible-language-server/blob/5568606/test/utils/yaml.test.ts#L24

**Comment by webknjaz** [comment]
> we should update the Windows jobs to run WSL2 instead of (or additionally to) the native runtime.

I've done some research and apparently, the VMs in GHA come without WSL2 (only WSL1 is available) and even if they did, they are running in an environment w/o hypervisor enabled (which would also be required). Here are some details on the latest available Windows VM: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md.

**Comment by ssbarnea** [comment]
Probably that is not the best place to store information about WSL testing. We need a new ticket specially for that. Maybe it would worth contacting github directly to ask about WSL1/2 testing under GHA. Somehow I have the impression that this is something Microsoft want to support...

Once I get my new laptop I will likely setup a Windows VM on it too and hopefully to spend bit more time learning about differences, how to detect environment and what we should do to help. For example the remoting support is not tested either. It appears to work but I do not trust things that do not have at least some basic testing on them.
