### ISSUE TITLE
Ansiblels Does Not Provide Completions

### ISSUE THREAD

**Issue by PriceHiller** [ansible/ansible-language-server#391]
### Summary

When using the latest version of `Ansiblels` I no longer get completions. After tracking it down, I no longer get completions after this commit: c695ba2b65630f246afe934a7acb7f6e97d2997b. Using the commit just prior (9211f4abd46988b6539d0357c4f2f3809450bb39), I am getting completions.

A gif of this in action:
![ansible-ls-failure](https://user-images.githubusercontent.com/58627896/176779349-baa5ccda-8d11-4a8e-baa1-fb4f39f86cb1.gif)

### Extension version

N/A

### VS Code version

N/A

### Ansible Version

```shell
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/Users/pricehiller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pricehiller/.pyenv/versions/3.10.2/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/pricehiller/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/pricehiller/.pyenv/versions/3.10.2/bin/ansible
  python version = 3.10.2 (main, Feb 15 2022, 21:01:48) [Clang 13.0.0 (clang-1300.0.29.30)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

macOS Monterey 12.4, ansible-lint 6.3.0, ansible 2.13.1

#### From Neovim's LSP log on the failing completion:

```
[ERROR][2022-06-30 16:13:37] ...lsp/handlers.lua:473	"An error occurred in 'onCompletion' handler: [TypeError] Cannot read properties of undefined (reading 'provideRedirectModules')\nTypeError: Cannot read properties of undefined (reading 'provideRedirectModules')\n    at /Users/pricehiller/.local/share/nvim/lsp_servers/ansiblels/out/server/src/providers/completionProvider.js:45:112\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/pricehiller/.local/share/nvim/lsp_servers/ansiblels/out/server/src/providers/completionProvider.js:5:58)"
```

**Comment by treatybreaker** [comment]
Seems to be only related to `ansible.completion.provideRedirectModules`, when I disable that in my configuration for the lsp I get completions.

**Comment by yaegassy** [comment]
If the language server side is to be adjusted, I feel it would be a good idea to add handling for cases where settings are not passed from the LSP client.

I don't know how to read Neovim's LSP log correctly, but it seems to be `undefined`, so.
