### ISSUE TITLE
Could not parse ansible-lint output when parseable output mode enabled

### ISSUE THREAD

**Issue by twouters** [ansible/ansible-language-server#43]
### Summary

When parseable mode is enabled for ansible-lint (`parseable: true` in `.ansible-lint`) the plugin is unable to parse ansible-lint's output.

~~I'm not sure if this is an issue of this plugin, or ansible-language-server.~~

```
[coc.nvim] Could not parse ansible-lint output. Please check your ansible-lint installation & configuration. More info in 
`Ansible Server` output.
```

output (`:CocCommand workspace.showOutput`) when parseable is enabled:

```
[Error  - 2:11:13 PM] Exception while parsing ansible-lint output: Unexpected token c in JSON at position 0
Tried to parse the following:
tasks/main.yml:144: package-latest Package installs should not use latest

[Info  - 2:11:13 PM] [ansible-lint] INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles:roles
WARNING  Listing 1 violation(s) that are fatal
You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - package-latest  # Package installs should not use latest

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

output when parseable is disabled:

```
[Info  - 2:13:34 PM] [ansible-lint] INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles:roles
You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - package-latest  # Package installs should not use latest

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

ansible-lint's output when parseable is enabled:

```
WARNING  Listing 3 violation(s) that are fatal
tasks/main.yml:118: yaml line too long (162 > 160 characters) (line-length)
tasks/main.yml:144: package-latest Package installs should not use latest
tasks/main.yml:289: yaml line too long (263 > 160 characters) (line-length)
You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - package-latest  # Package installs should not use latest
  - yaml  # Violations reported by yamllint

Finished with 3 failure(s), 0 warning(s) on 1 files.
```

ansible-lint's output when parseable is disabled:

```
WARNING  Listing 3 violation(s) that are fatal
yaml: line too long (162 > 160 characters) (line-length)
tasks/main.yml:118

package-latest: Package installs should not use latest
tasks/main.yml:144 Task/Handler: install dependencies

yaml: line too long (263 > 160 characters) (line-length)
tasks/main.yml:289

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - package-latest  # Package installs should not use latest
  - yaml  # Violations reported by yamllint

Finished with 3 failure(s), 0 warning(s) on 1 files.
```

### Extension version

0.1.1-0

### VS Code version

1.60

### Ansible Version

```shell
ansible [core 2.11.5] 
  config file = ~/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

### OS / Environment

Archlinux, vim + coc (@yaegassy/coc-ansible), ansible-lint 5.1.3

**Comment by ssbarnea** [comment]
@twouters Can you please test with latest extension 0.4.5? I do not even remember the version that you reported in original bug.

**Comment by twouters** [comment]
I've probably missed something, but I've mentioned the version that's included in package.json in this repo: https://github.com/ansible/ansible-language-server/blob/71d759ddc976b45fbd9f47ed9eff3065a47bdf20/package.json#L7

**Comment by yaegassy** [comment]
@ssbarnea @twouters Hi,

Currently, the version of `ansible-language-server` used by `coc-ansible` is `v0.1.1-0`.

This problem was reproduced in `vscode-ansible` (v0.4.5), of course.

<img width="1085" alt="ansible-language-server-issue43-1" src="https://user-images.githubusercontent.com/188642/135367123-41aee5db-c955-4ea3-9ea6-048d3714be31.png">

**Comment by yaegassy** [comment]
@ssbarnea 

Probably, `JSON.parse` failed in this part. <https://github.com/ansible/ansible-language-server/blob/main/src/services/ansibleLint.ts#L167>

And I think this message is being output on the catch side. <https://github.com/ansible/ansible-language-server/blob/main/src/services/ansibleLint.ts#L236-L239>

I think it needs to be adjusted in `ansible-language-server`.

**Comment by ssbarnea** [comment]
The bug is not inside the extension, I can confirm that the bug is inside ansible-lint. When parseable is configured to true in config file, it no longer matters what format is requested from the command line.

I am trying now to propose a fix for it.

**Comment by yaegassy** [comment]
@ssbarnea I understand about adjusting it on the `ansible-lint` side.

However, in versions of ansible-lint prior to `v5.1.3`, this error will continue to occur.

It might be helpful to add error handling for `json.parse`.

**Comment by ssbarnea** [comment]
True. In fact there is some error handling there but apparently it does not work as intended. Were you able to see the exact output from ansible-lint in the console log when the error occurred? Ideally we should also be able to check version of ansible-lint installed and require an upgrade if is below what we consider ok. A pull request would be appreciated here.
