### ISSUE TITLE
Noisy error message when creating a new file with vim (nvim.coc + coc-ansible)

### ISSUE THREAD

**Issue by twouters** [ansible/ansible-language-server#431]
### Summary

(Lazy copy+paste from ansible-lint since it's the third issue report about this :slightly_smiling_face: )

When opening an non-existing ansible file with vim, ansible-lint is triggered on the filename (should probably be the buffer contents instead of the filename but that's not up to ansible-lint at all) and ansible-lint spews a noisy exception.

See yaegassy/coc-ansible#26 for more details.

I think the question is: should ansible-lint be less verbose (again?) about a non-existent file or should Ansible languageserver be smarter with handling non-existent files? (Doing both is also an option :shrug: )

### Extension version

0.10.1

### VS Code version

1.71 (don't know)

### Ansible Version

```shell
ansible [core 2.13.3]
  config file = /home/twouters/.ansible.cfg
  configured module search path = ['/home/twouters/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/twouters/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Arch Linux

ansible-lint 6.5.2 using ansible 2.13.3

### Relevant log output

```shell
Please see yaegassy/coc-ansible#26
```

**Comment by yaegassy** [comment]
Here is a supplemental explanation of this issue.

In Vim/Neovim, when you add a new file, you first create what is called a buffer. Only when you save the buffer is the actual file created.

This results in a situation where ansible-lint is executed on a file that does not actually exist, resulting in an error.

**Comment by priyamsahoo** [comment]
@twouters, @yaegassy, could you please check if the error still exists? If not, feel free to close it.

**Comment by yaegassy** [comment]
@priyamsahoo This problem seems to be resolved by upgrading `ansible-lint`.
