### ISSUE TITLE
Warnings are displayed as errors

### ISSUE THREAD

**Issue by medanthelinium** [ansible/ansible-language-server#439]
### Summary

Both VSCode and Neovim (via [yaegassy/coc-ansible](https://github.com/yaegassy/coc-ansible)) display items that are listed under `warn_list` in a project's `ansible-lint` as errors, marking them red.

The `ansible-lint` itself is getting parsed by the plugin, because when the aforementioned items are moved from `warn_list` to `skip_list`, they aren't highlighted by ansible-language-server anymore.

### Extension version

0.13.59

### VS Code version

1.71.2

### Ansible Version

```shell
ansible [core 2.13.4]
  config file = None
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

macOS Monterey 12.5.1, ansible-lint 6.6.0 using ansible 2.13.4

### Relevant log output

```shell
[Trace - 5:30:43 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "/Users/username/Documents/check-coc-extension/ansible-check/roles/ntp/tasks/main.yml",
    "diagnostics": [
        {
            "message": "fqcn-builtins\nDescription: Use FQCN for builtin actions.",
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 2147483647
                }
            },
            "severity": 1,
            "source": "Ansible"
        },
        // ...snip
    ]
}
```

**Comment by ganeshrn** [comment]
@yaegassy Can you please take a look at this issue?

**Comment by yaegassy** [comment]
@ganeshrn  I checked with ALS 1.0.0. The problem seems to be ongoing.

After debugging the code, albeit briefly, there may be a bug in the detection of the `.ansible-lint` configuration file.

Therefore, it seems that the "severity" of diagnostics is not set to `warning`.

- https://github.com/ansible/ansible-language-server/blob/main/src/services/ansibleLint.ts#L200-L218

Maybe this area of "doValidate" is not behaving as expected.

- https://github.com/ansible/ansible-language-server/blob/main/src/services/ansibleLint.ts#L61-L76

**Comment by yaegassy** [comment]
I'll post the original issue link.

- https://github.com/yaegassy/coc-ansible/issues/27

**Comment by yaegassy** [comment]
I have built and tested the ALS for this commit. I believe this issue has been resolved in my environment.

- <https://github.com/ansible/ansible-language-server/pull/474>
- <https://github.com/ansible/ansible-language-server/pull/478>

**Comment by priyamsahoo** [comment]
Thanks for the update!
