### ISSUE TITLE
Document recommended way to run server

### ISSUE THREAD

**Issue by librick** [ansible/ansible-language-server#568]
### Problem

I'm using the following tools:
- Node Version Manager (nvm) (https://github.com/nvm-sh/nvm)
- zsh with ohmyzsh (https://github.com/ohmyzsh/ohmyzsh) 
- The ohmyzsh nvm plugin (https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/nvm)

I've installed ansible-language-server:
`npm install -g @ansible/ansible-language-server`  
Running `npm config get prefix` shows `~/.config/nvm/versions/node/v18.12.1/`,
and `ansible-language-server` is listed at `~/.config/nvm/versions/node/v18.12.1/bin/ansible-language-server`

I have the Ansible VSCode extension installed (Extension ID is `redhat.ansible`).
Now what?
- The ansible-language-server docs don't mention anything about actually running the server or suggestions on managing server lifetime
- The Ansible VSCode extension docs don't mention anything about ansible-language-server discovery or settings.

**What is the recommended way to run the ansible-language-server, and how do I configure the Ansible VSCode extension to use the server?** 

### Solution

Assume I'm ignorant of LSP details/internals. Improve the documentation to include the recommended way to run `ansible-language-server` and manage its lifetime such that it's usable by the Ansible VSCode extension, or otherwise document how the Ansible VSCode extension finds the running ansible-language-server.

### Additional context

I tried manually invoking the `ansible-language-server` script executable and got the following output:
```
Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'
```
What normally calls this script? The VSCode Ansible extension? If so, how the extension know where to look?

**Comment by ssbarnea** [comment]
Lamguage server is included in extension, as a user of the extension you do not need to do anything with it. Only developers wanting to write extensions for other IDEs might be interested to use it directly

**Comment by librick** [comment]
Having read the LSP spec and having spent some time looking though Neovim's LSP docs (https://neovim.io/doc/user/lsp.html#vim.lsp.start()), I think this issue is essentially the same as this one: https://github.com/ansible/ansible-language-server/issues/559. Closing this issue in favor of that one
