### ISSUE TITLE
AnsibleLS does not attach to buffer due to an error in LSP

### ISSUE THREAD

**Issue by rdxsuper** [ansible/ansible-language-server#586]
### Summary

I was able to capture debug logs for the AnsibleLS

Error log file attached to. Below is the snippet of the log
` "stderr"        "/home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token .\n    at createScript (vm.js:56:10)\n    at Object.runInThisContext (vm.js:97:10)\n    at Module._compile (module.js:549:28)\n    at Object.Module._extensions..js (module.js:586:10)\n    at Module.load (module.js:494:32)\n    at tryModuleLoad (module.js:453:12)\n    at Function.Module._load (module.js:445:3)\n    at Module.require (module.js:504:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n"`
[error_log.txt](https://github.com/ansible/ansible-language-server/files/11851128/error_log.txt)

### Extension version

1.1.0

### VS Code version

nvim v0.9.1

### Ansible Version

```shell
ansible 2.10.17
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/user/ansible/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### OS / Environment

CentOS 7

### Relevant log output

```shell
"stderr"        "/home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token .\n    at createScript (vm.js:56:10)\n    at Object.runInThisContext (vm.js:97:10)\n    at Module._compile (module.js:549:28)\n    at Object.Module._extensions..js (module.js:586:10)\n    at Module.load (module.js:494:32)\n    at tryModuleLoad (module.js:453:12)\n    at Function.Module._load (module.js:445:3)\n    at Module.require (module.js:504:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n"
```

**Comment by RasPintz** [comment]
+1 : 
uname: Debian 5.10.179-1

ansible 2.10.8
  config file = None
  configured module search path = ['/home/pintz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  
  nvim : NVIM v0.8.3 and NVIM v0.9.1

**Comment by RasPintz** [comment]
+1 : ""

```
ansible --version
ansible 2.10.8
  config file = /home/pintz/XXXXXX/ansible.cfg
  configured module search path = ['/home/pintz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110
  nvim --version
  NVIM v0.9.1
  ```
  
For the moment the only workaround I found is installing older version (via mason) in neovim : 

```
MasonInstall ansible-language-server@1.04
```

**Comment by priyamsahoo** [comment]
@rdxsuper, could you provide some more details about the issue?
We haven't received any such issue at our vscode ansible extension repository till now. Maybe it might be the case that it appears only in the neovim client.

**Comment by rdxsuper** [comment]
@priyamsahoo the same setup is working for me on another centos 7 instance. I am closing this issue as it may be related to the underlying nvim lua configuration and not the ansiblels itself.

**Comment by p3lim** [comment]
Exact same error on Ubuntu 22.04 LTS, fresh install of both npm and ansible-language-server.

**Comment by bolsen** [comment]
I tried this on Ubuntu 22.04. The use of the .? is  not supported in the NodeJS version that comes from the APT repository. I verified this by just doing a simple example of `a = 'test'; a?.length;`

One workaround is to install NVM (https://github.com/nvm-sh/nvm) and then install the latest LTS (`nvm install --lts`). It works for me now, because the current LTS version supports that operator.
