### ISSUE TITLE
Infinite loop on variable completion in roles

### ISSUE THREAD

**Issue by stasjok** [ansible/ansible-language-server#587]
### Summary

Every time I insert some jinja variable, `ansible-language-server` stops working and starts to consume 100% CPU.

My files layout:
* current directory has ansible playbooks
* `roles` directory contains my roles

Looks like it works for playbooks (files in current directory), but doesn't work in any of the task files in roles directory.

Steps to reproduce:

1) Create directories `mkdir -p ansible/roles/test/tasks`
2) `cd ansible`
3) Edit `test.yml` file. It's a playbook.
```yaml
- hosts: all
   vars:
     - some_var: 123
   tasks:
     - ansible.builtin.copy:
         src: "{{ so| }}" # completion works here
```
4) Edit `ansible/roles/test/tasks/main.yml`. It's a role task file.
```yaml
- ansible.builtin.copy:
     src: "{{ so| }}" # hangs on completion inside any jinja variable block {{ }}
```

### Extension version

1.1.0

### VS Code version

-

### Ansible Version

```shell
ansible [core 2.12.10]
  config file = /tmp/nix-shell.BhHQch/tmp.17jlaFU4zt/home/ansible/ansible.cfg
  configured module search path = ['/tmp/home-configuration-test/stas/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/jl5g2swxz0i4rhbp8x7qsn9mfpw5drql-python3.10-ansible-core-2.12.10/lib/python3.10/site-packages/ansible
  ansible collection location = /tmp/home-configuration-test/stas/home/.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/jl5g2swxz0i4rhbp8x7qsn9mfpw5drql-python3.10-ansible-core-2.12.10/bin/ansible
  python version = 3.10.12 (main, Jun  6 2023, 22:43:10) [GCC 12.3.0]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Debian 10. ansible-lint 6.17.1 using ansible-core:2.12.10 ruamel-yaml:0.17.21 ruamel-yaml-clib:0.2.7

**Comment by priyamsahoo** [comment]
Thanks for raising the issue. I will look into it.

**Comment by priyamsahoo** [comment]
Currently, we do not provide vars completion in a role or a task file. The vars completion is only limited to the playbook.
But, the issue of the language server being stuck when asked for vars completion is genuine, and a fix for the same has been made in this PR: #589.

Thanks.

**Comment by stasjok** [comment]
> Currently, we do not provide vars completion in a role or a task file.

For now I don't expect any, it looks very limiting even in playbooks. Potentially it could be very useful: it can complete for vars from roles default, roles vars, set_fact tasks, loop vars, register vars, ansible facts etc. Currently I downgraded language-server because current version is unusable (I use vars all the time and 95% of my playbooks just import roles...). Anyway thanks for fixing it.

**Comment by priyamsahoo** [comment]
We have that in our plans.
