### ISSUE TITLE
Using community.hashi_vault.vault_read gives fqcn warning

### ISSUE THREAD

**Issue by Wnthr** [ansible/ansible-language-server#633]
### Summary

TLDR: When using FCQN community.hashi_vault.vault_read, I get the warning `hashi should be hash`. ansible-lint produces 0 failures, 0 warnings.

### Extension version

unknown

### VS Code version

NVIM v0.9.5

### Ansible Version

```shell
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/home/foouser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/foouser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/python-exec/python3.11/ansible
  python version = 3.11.7 (main, Feb  2 2024, 21:09:42) [GCC 11.3.0] (/usr/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

### OS / Environment

Gentoo Linux, ansible-lint 6.22.1

**Comment by audgirka** [comment]
@Wnthr We do not support NVIM.
Also, it seems that this message is coming from spell checker.

Thanks
