### ISSUE TITLE
Straighten out version numbering and make a new release

### ISSUE THREAD

**Issue by jcgruenhage** [ansible/ansible-language-server#64]
### Problem

There's 0.1.0, 0.1.0-1 and 0.1.1-0 available on npm, 1.0.0, 1.0.1 and 1.0.2 in git, and both of those haven't seen an update in a while. The tags in git and versions on npm should be easy to match up.

### Solution

- Make a new release, ideally with a clear versioning policy
- Yank the old versions from git and npm

### Additional context

I'm currently packaging this for Void Linux, having a tagged release would be very helpful here.

**Comment by jcgruenhage** [comment]
Yep, that sounds good. Thanks for your work on this!

**Comment by jcgruenhage** [comment]
Great, I've updated void-linux/void-packages#33519 to the 0.2.0-beta release, and hope it'll get merged soon after the proper 0.2.0 release. Thanks!

**Comment by webknjaz** [comment]
I think we'll have a v0.2.3 release today/tomorrow as this PR https://github.com/ansible/ansible-language-server/pull/80 gets merged.

**Comment by jcgruenhage** [comment]
My last question was not meant to be regarding how many prereleases should be done and what kind of prereleases they are supposed to be, just how the prereleases are named.

What you are doing is changing the version number on each prerelease and on the final release, what others are doing usually (at least as far as I've seen) is keeping the version number the same and just changing the prerelease suffix, so v0.2.0-beta.1 and v0.2.0-beta.2 instead of v0.2.0-beta and v0.2.1-beta.

Does that make sense? Not sure how else to put it. D:
